mon_compte:
  path: /mon-compte
  controller: App\Controller\UserController::monCompte

admin_index:
  path: /admin
  controller: App\Controller\UserController::adminIndex

admin_add_product:
  path: /admin/ajouter-produit
  controller: App\Controller\UserController::adminAddProduct

admin_list_product:
  path: /admin/liste-produits
  controller: App\Controller\UserController::adminListProduct

admin_add_user:
  path: /admin/ajouter-utilisateur
  controller: App\Controller\UserController::adminAddUser

admin_list_user:
  path: /admin/liste-utilisateurs
  controller: App\Controller\UserController::adminListUser
